// AUTO-GENERATED by scripts/gen_ir_schema.py — do not edit by hand.
//
// Maps each IR node type to its declared fields and the set of value types
// each field is allowed to carry, derived from the Python annotations in
// papyri/nodes.py. The viewer's IR stats panel uses this to surface
// 0-counts: union members and fields that *could* exist but were never
// observed in any scanned bundle.

export interface IRFieldSchema {
  /** True when the field is tuple[T, ...] or list[T] at the top level. */
  array: boolean;
  /** Sorted list of legal value-type tags (IR class names + primitive tags). */
  types: readonly string[];
}

export type IRSchema = Readonly<Record<string, Readonly<Record<string, IRFieldSchema>>>>;

export const IR_SCHEMA: IRSchema = {
  Admonition: {
    base_type: {
      array: false,
      types: ["string"],
    },
    children: {
      array: true,
      types: [
        "Admonition",
        "AdmonitionTitle",
        "Blockquote",
        "BulletList",
        "Citation",
        "Code",
        "Comment",
        "DefList",
        "DefListItem",
        "Directive",
        "FieldList",
        "Figure",
        "Footnote",
        "Image",
        "Math",
        "Paragraph",
        "Table",
        "Target",
        "ThematicBreak",
        "Unimplemented",
        "UnprocessedDirective",
        "[]",
      ],
    },
    kind: {
      array: false,
      types: ["string"],
    },
  },
  AdmonitionTitle: {
    children: {
      array: true,
      types: [
        "CitationReference",
        "CrossRef",
        "Emphasis",
        "FootnoteReference",
        "Image",
        "InlineCode",
        "InlineMath",
        "InlineRole",
        "Link",
        "ParamRef",
        "Strong",
        "SubstitutionRef",
        "Text",
        "Unimplemented",
        "[]",
        "null",
      ],
    },
  },
  Blockquote: {
    children: {
      array: true,
      types: [
        "Admonition",
        "Blockquote",
        "BulletList",
        "Citation",
        "Code",
        "Comment",
        "DefList",
        "DefListItem",
        "Directive",
        "FieldList",
        "Figure",
        "Footnote",
        "Image",
        "Math",
        "Paragraph",
        "Table",
        "Target",
        "ThematicBreak",
        "UnprocessedDirective",
        "[]",
      ],
    },
  },
  BulletList: {
    children: {
      array: true,
      types: ["ListItem", "[]"],
    },
    ordered: {
      array: false,
      types: ["boolean"],
    },
    start: {
      array: false,
      types: ["number"],
    },
  },
  Citation: {
    children: {
      array: true,
      types: ["Paragraph", "[]"],
    },
    label: {
      array: false,
      types: ["string"],
    },
  },
  CitationReference: {
    label: {
      array: false,
      types: ["string"],
    },
  },
  Code: {
    execution_status: {
      array: false,
      types: ["null", "string"],
    },
    out: {
      array: false,
      types: ["string"],
    },
    value: {
      array: false,
      types: ["string"],
    },
  },
  CrossRef: {
    kind: {
      array: false,
      types: ["string"],
    },
    reference: {
      array: false,
      types: ["LocalRef", "RefInfo"],
    },
    value: {
      array: false,
      types: ["string"],
    },
  },
  DefList: {
    children: {
      array: true,
      types: ["DefListItem", "[]"],
    },
  },
  DefListItem: {
    dd: {
      array: true,
      types: [
        "Admonition",
        "Blockquote",
        "BulletList",
        "Code",
        "DefList",
        "Directive",
        "FieldList",
        "Math",
        "Paragraph",
        "Table",
        "Target",
        "TocTree",
        "Unimplemented",
        "UnimplementedInline",
        "UnprocessedDirective",
        "[]",
      ],
    },
    dt: {
      array: false,
      types: ["Link", "Paragraph", "Text", "UnimplementedInline"],
    },
  },
  DocParam: {
    annotation: {
      array: false,
      types: ["string"],
    },
    desc: {
      array: true,
      types: [
        "Admonition",
        "Blockquote",
        "BulletList",
        "Code",
        "DefList",
        "DefListItem",
        "Directive",
        "Figure",
        "Math",
        "Paragraph",
        "SubstitutionDef",
        "Table",
        "UnprocessedDirective",
        "[]",
      ],
    },
    name: {
      array: false,
      types: ["string"],
    },
  },
  DocstringSentinel: {
    message: {
      array: false,
      types: ["string"],
    },
  },
  Emphasis: {
    children: {
      array: true,
      types: [
        "CitationReference",
        "CrossRef",
        "Emphasis",
        "FootnoteReference",
        "Image",
        "InlineCode",
        "InlineMath",
        "InlineRole",
        "Link",
        "ParamRef",
        "Strong",
        "SubstitutionRef",
        "Text",
        "Unimplemented",
        "[]",
      ],
    },
  },
  Empty: {},
  FieldList: {
    children: {
      array: true,
      types: ["FieldListItem", "[]"],
    },
  },
  FieldListItem: {
    body: {
      array: true,
      types: ["Code", "Directive", "Paragraph", "Text", "[]"],
    },
    name: {
      array: true,
      types: ["Code", "Text", "[]"],
    },
  },
  Figure: {
    value: {
      array: false,
      types: ["RefInfo"],
    },
  },
  Footnote: {
    children: {
      array: true,
      types: ["Paragraph", "[]"],
    },
    label: {
      array: false,
      types: ["string"],
    },
  },
  FootnoteReference: {
    label: {
      array: false,
      types: ["string"],
    },
  },
  Image: {
    alt: {
      array: false,
      types: ["string"],
    },
    url: {
      array: false,
      types: ["string"],
    },
  },
  InlineCode: {
    value: {
      array: false,
      types: ["string"],
    },
  },
  InlineMath: {
    value: {
      array: false,
      types: ["string"],
    },
  },
  InlineRole: {
    domain: {
      array: false,
      types: ["null", "string"],
    },
    inventory: {
      array: false,
      types: ["null", "string"],
    },
    role: {
      array: false,
      types: ["null", "string"],
    },
    value: {
      array: false,
      types: ["string"],
    },
  },
  Link: {
    children: {
      array: true,
      types: [
        "CitationReference",
        "CrossRef",
        "Emphasis",
        "FootnoteReference",
        "Image",
        "InlineCode",
        "InlineMath",
        "InlineRole",
        "ParamRef",
        "Strong",
        "SubstitutionRef",
        "Text",
        "Unimplemented",
        "[]",
      ],
    },
    title: {
      array: false,
      types: ["string"],
    },
    url: {
      array: false,
      types: ["string"],
    },
  },
  ListItem: {
    children: {
      array: true,
      types: [
        "Admonition",
        "Blockquote",
        "BulletList",
        "Citation",
        "CitationReference",
        "Code",
        "Comment",
        "CrossRef",
        "DefList",
        "DefListItem",
        "Directive",
        "Emphasis",
        "FieldList",
        "Figure",
        "Footnote",
        "FootnoteReference",
        "Image",
        "InlineCode",
        "InlineMath",
        "InlineRole",
        "Link",
        "Math",
        "Paragraph",
        "ParamRef",
        "Strong",
        "SubstitutionRef",
        "Table",
        "Target",
        "Text",
        "ThematicBreak",
        "Unimplemented",
        "UnprocessedDirective",
        "[]",
      ],
    },
  },
  LocalRef: {
    kind: {
      array: false,
      types: ["string"],
    },
    path: {
      array: false,
      types: ["string"],
    },
  },
  Math: {
    value: {
      array: false,
      types: ["string"],
    },
  },
  NumpydocExample: {
    value: {
      array: true,
      types: ["[]", "string"],
    },
  },
  NumpydocSeeAlso: {
    value: {
      array: true,
      types: ["SeeAlsoItem", "[]"],
    },
  },
  NumpydocSignature: {
    value: {
      array: false,
      types: ["string"],
    },
  },
  Options: {
    values: {
      array: true,
      types: ["[]", "string"],
    },
  },
  Paragraph: {
    children: {
      array: true,
      types: [
        "CitationReference",
        "CrossRef",
        "Emphasis",
        "FootnoteReference",
        "Image",
        "InlineCode",
        "InlineMath",
        "InlineRole",
        "Link",
        "ParamRef",
        "Strong",
        "SubstitutionRef",
        "Text",
        "Unimplemented",
        "UnimplementedInline",
        "[]",
      ],
    },
  },
  ParamRef: {
    name: {
      array: false,
      types: ["string"],
    },
  },
  Parameters: {
    children: {
      array: true,
      types: ["DocParam", "[]"],
    },
  },
  RefInfo: {
    kind: {
      array: false,
      types: ["string"],
    },
    module: {
      array: false,
      types: ["null", "string"],
    },
    path: {
      array: false,
      types: ["string"],
    },
    version: {
      array: false,
      types: ["null", "string"],
    },
  },
  Root: {
    children: {
      array: true,
      types: [
        "Admonition",
        "Blockquote",
        "BulletList",
        "Citation",
        "Code",
        "Comment",
        "DefList",
        "DefListItem",
        "Directive",
        "FieldList",
        "Figure",
        "Footnote",
        "Image",
        "Math",
        "Paragraph",
        "Parameters",
        "SignatureNode",
        "SubstitutionDef",
        "Table",
        "Target",
        "ThematicBreak",
        "Unimplemented",
        "UnprocessedDirective",
        "[]",
      ],
    },
  },
  Section: {
    children: {
      array: true,
      types: [
        "Admonition",
        "Blockquote",
        "BulletList",
        "Citation",
        "Code",
        "Comment",
        "DefList",
        "Directive",
        "DocstringSentinel",
        "FieldList",
        "Figure",
        "Footnote",
        "Image",
        "Math",
        "Options",
        "Paragraph",
        "Parameters",
        "SubstitutionDef",
        "SubstitutionRef",
        "Table",
        "Target",
        "Text",
        "ThematicBreak",
        "Unimplemented",
        "UnimplementedInline",
        "UnprocessedDirective",
        "[]",
      ],
    },
    level: {
      array: false,
      types: ["number"],
    },
    target: {
      array: false,
      types: ["null", "string"],
    },
    title: {
      array: true,
      types: [
        "CitationReference",
        "CrossRef",
        "Emphasis",
        "FootnoteReference",
        "Image",
        "InlineCode",
        "InlineMath",
        "InlineRole",
        "Link",
        "ParamRef",
        "Strong",
        "SubstitutionRef",
        "Text",
        "Unimplemented",
        "[]",
      ],
    },
  },
  SeeAlsoItem: {
    descriptions: {
      array: true,
      types: ["Paragraph", "[]"],
    },
    name: {
      array: false,
      types: ["CrossRef"],
    },
    type: {
      array: false,
      types: ["null", "string"],
    },
  },
  SigParam: {
    annotation: {
      array: false,
      types: ["Empty", "null", "string"],
    },
    default: {
      array: false,
      types: ["Empty", "null", "string"],
    },
    kind: {
      array: false,
      types: ["string"],
    },
    name: {
      array: false,
      types: ["string"],
    },
  },
  SignatureNode: {
    kind: {
      array: false,
      types: ["string"],
    },
    parameters: {
      array: true,
      types: ["SigParam", "[]"],
    },
    return_annotation: {
      array: false,
      types: ["Empty", "string"],
    },
    target_name: {
      array: false,
      types: ["string"],
    },
  },
  Strong: {
    children: {
      array: true,
      types: [
        "CitationReference",
        "CrossRef",
        "Emphasis",
        "FootnoteReference",
        "Image",
        "InlineCode",
        "InlineMath",
        "InlineRole",
        "Link",
        "ParamRef",
        "Strong",
        "SubstitutionRef",
        "Text",
        "Unimplemented",
        "[]",
      ],
    },
  },
  SubstitutionDef: {
    children: {
      array: true,
      types: ["Directive", "UnprocessedDirective", "[]"],
    },
    value: {
      array: false,
      types: ["string"],
    },
  },
  SubstitutionRef: {
    value: {
      array: false,
      types: ["string"],
    },
  },
  Table: {
    children: {
      array: true,
      types: ["TableRow", "[]"],
    },
  },
  TableCell: {
    children: {
      array: true,
      types: [
        "Admonition",
        "Blockquote",
        "BulletList",
        "Citation",
        "CitationReference",
        "Code",
        "Comment",
        "CrossRef",
        "DefList",
        "DefListItem",
        "Directive",
        "Emphasis",
        "FieldList",
        "Figure",
        "Footnote",
        "FootnoteReference",
        "Image",
        "InlineCode",
        "InlineMath",
        "InlineRole",
        "Link",
        "Math",
        "Paragraph",
        "ParamRef",
        "Strong",
        "SubstitutionRef",
        "Table",
        "Target",
        "Text",
        "ThematicBreak",
        "Unimplemented",
        "UnprocessedDirective",
        "[]",
      ],
    },
  },
  TableRow: {
    children: {
      array: true,
      types: ["TableCell", "[]"],
    },
    header: {
      array: false,
      types: ["boolean"],
    },
  },
  Target: {
    label: {
      array: false,
      types: ["string"],
    },
    url: {
      array: false,
      types: ["null", "string"],
    },
  },
  Text: {
    value: {
      array: false,
      types: ["string"],
    },
  },
  ThematicBreak: {},
  TocTree: {
    children: {
      array: true,
      types: ["TocTree", "[]"],
    },
    ref: {
      array: false,
      types: ["LocalRef"],
    },
    title: {
      array: false,
      types: ["string"],
    },
  },
  Unimplemented: {
    placeholder: {
      array: false,
      types: ["string"],
    },
    value: {
      array: false,
      types: ["string"],
    },
  },
  UnimplementedInline: {
    children: {
      array: true,
      types: ["Text", "[]"],
    },
  },
} as const;
