[global]
module = 'dask'
logo = "img/dask-logo.png"
submodules = ["array"]
exclude = [ "dask.utils:Dispatch",
            # numpydoc parse error
            'dask.typing:_NoDefault',
            # target not implemented
            'dask.highlevelgraph:HighLevelGraph.visualize',
            'dask.array.overlap:map_overlap',
            # AssertionError : Serialisation proble
            "dask.array.routines:matmul",
            "dask.array.routines:rot90",
            # visit_target not implemented
            "dask.array.reshape:reshape",
            "dask.array.tiledb_io:to_tiledb",
            # visit_comment not implemented
            "dask.array.routines:unique",
            # misc aseert
            "dask.base:replace_name_in_key",
            #"ExecError-<class 'ValueError'>": [
            "dask.array.core:to_npy_stack",
            #"NumpydocError-<class 'numpydoc.docscrape.ParseError'>": [
            "dask.array.slicing:slice_array",
            # unbalanced backticks,
            # need fix in numpy
            "dask.array.ufunc:frexp", # https://github.com/numpy/numpy/pull/21020
            # imbalanced backticks, need dask fix. https://github.com/dask/dask/pull/8693
            "dask.array.reductions:cumreduction",
            # "ErrorHelper1-<class 'AssertionError'>": [
            "dask.array.routines:tensordot",
            "dask.utils:tensordot",
            "dask.array.slicing:replace_ellipsis",
            "dask.array.overlap:sliding_window_view",
            "dask.array.overlap:ensure_minimum_chunksize",
            "dask.array.overlap:overlap",
            "dask.array.overlap:sliding_window_view"
  ]


#docs_path = "~/dev/dask/docs/source"
exec_failure = 'fallback'
execute_doctests = false
